### ISSUE TITLE
does not work sometimes

### ISSUE THREAD

**Issue by khvolk** [mcauser/micropython-am2320#4]
I used an AM2320 with this library with good results. But today I got:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "am2320.py", line 44, in measure
OSError: [Errno 19] ENODEV

after starting sensor.measure(). Adding two 1 kOhm resistors (SDA to 3.3V, SDL to 3.3V) solve this problem.

**Comment by mcauser** [comment]
Hi @khvolk you're correct. To use the I2C interface, your SDA+SCL lines need pull up resistors.
I'll update the docs so it's more clear that they are required.

**Comment by jcksnvllxr80** [comment]
Have you tried this with a pi pico?
