### ISSUE TITLE
CRC/checksum Error

### ISSUE THREAD

**Issue by jcksnvllxr80** [mcauser/micropython-am2320#5]
I am getting CRC error with pi pico. Can you tell what might be going on here?
I printed the buffer after the read and get the following

`b'\x03\x04\x01\xf9\x00\xa1\xaf\x00'`

so i set buf equal to the above

`buf = b'\x03\x04\x01\xf9\x00\xa1\xaf\x00'`

Next, I manually ran a few lines to see what was going on and possibly find a work around.

`a = crc16(buf[:-2])`
> a -> 40417

`b = ustruct.unpack('<H', bytearray(buf[-2:]))[0]`
> b -> 175

`if (b != a):
            raise Exception("checksum error")`
            
 Maybe this is an issue related to raspberry pi pico?

**Comment by jcksnvllxr80** [comment]
You can close this issue. It was due to the pi pico having a 2 byte read register I suppose. I fixed it in the constructor by using 
`self.buf = bytearray(16)`
instead of
`self.buf = bytearray(8)`

**Comment by mcauser** [comment]
I removed the `ustruct` dependency in the latest version. Replaced with a simple bit shift. `x << 8 | y`
